services:
  mariadb:
    image: mariadb:10.6
    environment:
      MARIADB_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
  registrofazenda-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mariadb

volumes:
  data:
