spring:
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}/registro_animais?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: admin
  output:
    ansi:
      enabled: ALWAYS
logging:
  file:
    path: logs
